### ISSUE TITLE
markup tags autoexported into Bib(La)TeX key, if at start of title

### ISSUE THREAD

**Issue by katrinleinweber** [rokondo/Zotero-autoexporting#8]
Markup tags at the start of a title (`<i>Species name</i>`) are autoexported into the Bib(La)TeX key (`@article{author_<i>Species...}`), causing [errors](https://stackoverflow.com/questions/22640467/how-can-i-add-a-bibliography-with-knitr) downstream. This happens for me with [Zotero Autoexport 1.1.9.1](https://addons.mozilla.org/en-US/firefox/addon/zotero-bib-autoexport/) in Firefox 35.0.1, but not upon manual .bib export from Zotero itself. OS is Win7 64bit.

**Comment by katrinleinweber** [comment]
PS: If only a single word is marked up, the above problem occurs with the closing tag: `<i>Species</i>` => `@article{author_Species</i>...}`

**Comment by rokondo** [comment]
First of all thanks for your contribution for my addon :) and to provide some feedback.

I checked your issue and if i export it with right clicking at collection i get this result: `@book{_<i>speecies</i>_????,
	title = {\textit{Speecies}}
}`

In general if there are differences between original and my export It might a problem of my code for sure. But my code only adjust some minimal settings and then runs the normal export of the Zotero. Can you create me a zotero rdf or something which i can use for test?

**Comment by katrinleinweber** [comment]
You're welcome :-) Will try to send you demo files next week. On a Mac just now, Zotero's manual export creates these errors as well!?!

**Comment by katrinleinweber** [comment]
This problem does indeed occur because of Zotero itself, not your plugin. It's being tracked in zotero/translators/issues/853. My apologies for this inaccurate bug report!

**Comment by rokondo** [comment]
well thanks - nope (:
