### ISSUE TITLE
no option to configure character encoding

### ISSUE THREAD

**Issue by tristan-k** [rokondo/Zotero-autoexporting#9]
There is no option to configure the character encoding, as it is possible in the export dialog. This is imported for exporting properly with entries which include diacritic characters. 

![ishot-1](https://cloud.githubusercontent.com/assets/732025/7207897/02f556a8-e53d-11e4-9ee0-598c4e3fcb33.jpg)

**Comment by rokondo** [comment]
Well you are right, but the problem is that I have no influence on options relating the translator. I can only show options (and control) which Zotero has. Else you have to use a special translator maybe, and then you will be free to use with my addon too. What is the exact problem?

**Comment by tristan-k** [comment]
I've to export into Unicode UTF-8 because of german Umlauts. I use autoexport together with Zettelkasten (http://zettelkasten.danielluedecke.de/), which provides an options to import bibtex data. Without configuring the character encoding the entries with diacritics in Zettelkasten end up garbeled.

**Comment by rokondo** [comment]
Hey sorry needed some time to research the issue with your export. I have to code some circumstandes with the official Zotero code but you might try, the beta I created for you:http://rokdd.de/private/programmierung/zotero-autoexporting/releases/zotero-autoexporting-1-1-9-3.xpi

Please let me know whether it worked for you or even not.

**Comment by tristan-k** [comment]
Thanks! That works very well. Much appreciated.
